name: Automated Tests

on: pull_request

jobs:
  test:
    name: Ubuntu Test
    runs-on: Ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Build with Maven
        run: mvn clean install --batch-mode
      - name: Run tests
        run: mvn test --batch-mode

